### ISSUE TITLE
Version 1.9.4 broken in Runestone

### ISSUE THREAD

**Issue by bnmnetp** [bjones1/CodeChat#20]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.10/site-packages/sphinx/application.py", line 259, in __init__
    self._post_init_env()
  File "/usr/local/lib/python3.10/site-packages/sphinx/application.py", line 318, in _post_init_env
    self.env.find_files(self.config, self.builder)
  File "/usr/local/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 416, in find_files
    self.project.discover(exclude_paths, self.config.include_patterns)
  File "/usr/local/lib/python3.10/site-packages/sphinx/project.py", line 44, in discover
    docname = self.path2doc(filename)
  File "/usr/local/lib/python3.10/site-packages/CodeChat/CodeToRestSphinx.py", line 215, in _path2doc
    return self._path_to_docname[filename]  # type: ignore[index]
AttributeError: 'Project' object has no attribute '_path_to_docname'
```

Reverting to 1.92. works fine

**Comment by bjones1** [comment]
Thanks! I'll fix -- I changed CodeChat to work with Sphinx 7.2.6, but that obviously breaks old Sphinx versions. I'll put the old code back in.

**Comment by bjones1** [comment]
On second thought, I'd just update the dependencies for Runestone -- the only important changes are fixes for newer Sphinx versions.
